#!/usr/bin/fish
cargo build

echo 123456789\|123456789\|123456789\|123456789\|123456789\|123456789\|123456789\| | ./target/debug/kijetesantakaluotokieni

echo 123456789\|123456789\|123456789\|123456789\|123456789\|123456789\|123456789\| | ./target/debug/kijetesantakaluotokieni --pakala 60

echo "Белеет парус одинокий 
В тумане моря голубом!.. 
Что ищет он в стране далекой? 
Что кинул он в краю родном?..
 
A lonely sail is flashing white
Amdist the blue mist of the sea!...
What does it seek in foreign lands?
What did it leave behind at home?.." | ./target/debug/kijetesantakaluotokieni --poki "~3Ew/\\\\/"

echo | ./target/debug/kijetesantakaluotokieni

echo mu | ./target/debug/kijetesantakaluotokieni --nimi soweli 

echo 1234567890123 | ./target/debug/kijetesantakaluotokieni
echo 12345678901234 | ./target/debug/kijetesantakaluotokieni
echo Pingo pi n\'t go li sitelen | ./target/debug/kijetesantakaluotokieni --pilin --kule unu  --kule suli --nimi lili 

figlet the nineties | ./target/debug/kijetesantakaluotokieni --pakala-ala
