#!/usr/bin/fish
# this test script relies on things that exist on our computer which probably don't exist on yours. it is not meant to be a demonstration. we have been using it solely for debugging as we work.


set -lx NASINKIJE "$HOME/z/preciouskijes/"

cargo build

echo 123456789\|123456789\|123456789\|123456789\|123456789\|123456789\|123456789\| | ./target/debug/kijetesantakaluotokieni

echo 123456789\|123456789\|123456789\|123456789\|123456789\|123456789\|123456789\| | ./target/debug/kijetesantakaluotokieni --pakala 60

echo "Белеет парус одинокий 
В тумане моря голубом!.. 
Что ищет он в стране далекой? 
Что кинул он в краю родном?..
 
A lonely sail is flashing white
Amdist the blue mist of the sea!...
What does it seek in foreign lands?
What did it leave behind at home?.." | ./target/debug/kijetesantakaluotokieni --poki "w3Em/\\\\/"

echo | ./target/debug/kijetesantakaluotokieni

echo mu | ./target/debug/kijetesantakaluotokieni --nimi soweli 

echo mi wile e supa lape   | ./target/debug/kijetesantakaluotokieni --lape 
echo 12345678901234 | ./target/debug/kijetesantakaluotokieni
echo Pingo pi n\'t go li sitelen | ./target/debug/kijetesantakaluotokieni --pilin --kule unu  --kule suli -b --nimi kije-lili 

figlet the nineties | ./target/debug/kijetesantakaluotokieni --pakala-ala -f yupekosi

./target/debug/kijetesantakaluotokieni -l
for name in (./target/debug/kijetesantakaluotokieni -l | string split " ");
    ./target/debug/kijetesantakaluotokieni -f $name mu;
end;


./target/debug/kijetesantakaluotokieni -f kijetonsitakalu mu
./target/debug/kijetesantakaluotokieni -f kijetonsitakatu  mu
./target/debug/kijetesantakaluotokieni -f kuletesantakalu  mu